<Palette>:
    MDBoxLayout:
        orientation: "vertical"
        MDBoxLayout:
            id: primary
            MDBoxLayout:
                md_bg_color: app.theme_cls.primary_light
            MDBoxLayout:
                md_bg_color: app.theme_cls.primary_color
            MDBoxLayout:
                md_bg_color: app.theme_cls.primary_dark

        MDBoxLayout:
            id: bg
            MDBoxLayout:
                md_bg_color: app.theme_cls.bg_darkest
            MDBoxLayout:
                md_bg_color: app.theme_cls.bg_dark
            MDBoxLayout:
                md_bg_color: app.theme_cls.bg_normal
            MDBoxLayout:
                md_bg_color: app.theme_cls.bg_light

        MDBoxLayout:
            id: opp_bg
            MDBoxLayout:
                md_bg_color: app.theme_cls.opposite_bg_darkest
            MDBoxLayout:
                md_bg_color: app.theme_cls.opposite_bg_dark
            MDBoxLayout:
                md_bg_color: app.theme_cls.opposite_bg_normal
            MDBoxLayout:
                md_bg_color: app.theme_cls.opposite_bg_light

        MDBoxLayout:
            id: extras
            MDBoxLayout:
                md_bg_color: app.theme_cls.divider_color
            MDBoxLayout:
                md_bg_color: app.theme_cls.text_color
            MDBoxLayout:
                md_bg_color: app.theme_cls.secondary_text_color
            MDBoxLayout:
                md_bg_color: app.theme_cls.icon_color


<Frame>:
    MDBoxLayout:
        orientation: "vertical"
        MDToolbar:
            title: "Hey there"

        MDBoxLayout:
            MDNavigationRail:
                id: rail
                md_bg_color: app.theme_cls.bg_dark

                use_action_button: True
                action_icon_button: "book-plus"
                action_color_button: app.theme_cls.primary_color
                on_action_button: print(sm.screens)

                color_active: app.theme_cls.primary_dark
                use_hover_behavior: True

                visible: "Unlabeled"

                MDNavigationRailItem:
                    icon: "snowflake"
                    on_press: sm.current = "2"

                MDNavigationRailItem:
                    icon: "book-account"
                    on_press: sm.current = "1"



            ScreenManager:
                id: sm

                Screen:
                    name: "1"
                    MultiFile1:

                Screen:
                    name: "2"

                    MultiFile2:
